### ISSUE TITLE
Handling of CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by hendrikebbers** [hiero-ledger/.github#7]
The LFDT guideline says that every repository needs a `CODE_OF_CONDUCT.md` file: https://lf-decentralized-trust.github.io/governance/governing-documents/repository-structure.html

Today, we have `CODE_OF_CONDUCT.md` in the https://github.com/hiero-ledger/.github repository. By doing so, it is shown in every repo of the organization. I assume that is good enough, but I want to double check if it is valid.

**Comment by ryjones** [comment]
yes
